accounts/urls.py
from django.urls import path
from  . import views

app_name='accounts'

urlpatterns = [
	path('signup',views.signup,name='signup'),
	path('profile',views.profile,name='profile'),
    path('<int:id>/edit',views.profile_edit,name='profile_edit'),
     

]

kito/urls.py
from django.urls import path
from . import views

app_name='kito'

urlpatterns = [

    path('kito_list',views.kito_list,name='kito_list'),
    path('add', views.add_daykito, name='add_daykito'),
    path('<str:slug>/edit',views.edit,name='edit'),
    path('list_delete/<str:slug>',views.deleteList,name='list_delete'),



    path('add-haeder', views.add_haeder, name='add_haeder'),
    path('<str:slug>/edit-header',views.edit_header,name='edit_header'),
    path('header_delete/<str:slug>',views.delete_header,name='delete_header'),


    path('add-cook', views.add_cook, name='add_cook'),
    path('<str:slug>/edit-cook',views.edit_cook,name='edit_cook'),
    path('cook_delete/<str:slug>',views.delete_cook,name='delete_cook'),
    
    # path('categories',views.all_categories,name='all_categories'),
    # path('categories/<int:id>',views.category_ads,name='category_ads'),
    # path('<int:id>/edit',views.post_edit,name='post_edit'),
    # path('delete/<int:id>/',views.delete_List, name='delete_list'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

def home(request):
    return redirect('kito:kito_list')

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls',namespace='accounts')),
    path('',  home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('kito.urls', namespace='kito')),
]
if settings.DEBUG:

    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from  django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class  Profile(models.Model):
    user  = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/')
    bio   = models.TextField(blank=True,max_length=250)
    def __str__(self):
        return self.user.username
    
    
 
        return "/static/images/user.jpg"
@receiver(post_save, sender=User) 
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
   

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from  django.contrib.auth.models import User
from  .models import Profile
# from .models import

class UserForm(UserCreationForm):

    class  Meta:
        model = User
        fields = ['username','email','password1','password1']



class ProfileEditForm(forms.ModelForm):

    class  Meta:
    	
        model = Profile
        fields = ['user','image','bio']
        
class UserEditForm(forms.ModelForm):
    
    class  Meta:
        model = User
        fields = ['username','first_name','last_name','email']

accounts/views.py
from django.shortcuts import render,redirect
from  .forms import UserForm,UserEditForm,ProfileEditForm
from .models import  Profile
from django.contrib.auth.decorators import login_required
from  django.contrib.auth import  authenticate, login
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/accounts/profile')

    else:
        form = UserForm()
    return render(request, 'registration/signup.html',{'form':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})


@login_required
def profile_edit(request,id):
    profile = Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform = UserEditForm(request.POST, instance=request.user)
        profileform = ProfileEditForm(request.POST, instance=profile)
        if userform.is_valid() and  profileform.is_valid():
            userform.save()
            myform = profileform.save(commit=False)
            myform.user = request.user
            myform.save()
            return redirect('/accounts/profile')

    else:
        userform=UserEditForm(instance=request.user)
        profileform=ProfileEditForm(instance=profile)

    return render(request,'accounts/edit-profile.html',{'profile':profile,
                                                        'profileform':profileform,
                                                        'userform':userform})

accounts/templates/accounts/edit-profile.html
{% extends "base.html" %} {% load bootstrap4 %} {% block content%}

    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Edit Profile </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form profileform  %}
                {% bootstrap_form userform  %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Save Edit</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %} 
  {% block content%}

<!-- Submit Ad -->
 <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Profile</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
     
              <img src="{{ profile.image.url }}" alt="">
               
              
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4><h3>{{profile}}</h3></h4>
              <p>{{profile.bio}}.</p>
              <ul class="social-icons">
                </li>
                <li><a href="{% url 'accounts:profile_edit' profile.id %}">Edit</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'kito:add_haeder' %}">Add Post Heder</a></li>
                <li><a href="{% url 'kito:add_cook' %}">Add Post Cook</a></li>
                <li>

                  
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>


 
<!-- // Submit Ad -->
{% endblock %}