kito/urls.py
from django.urls import path
from . import views

app_name='kito'

urlpatterns = [

    path('kito_list',views.kito_list,name='kito_list'),
    path('add', views.add_daykito, name='add_daykito'),
    path('<str:slug>/edit',views.edit,name='edit'),
    path('list_delete/<str:slug>',views.deleteList,name='list_delete'),



    path('add-haeder', views.add_haeder, name='add_haeder'),
    path('<str:slug>/edit-header',views.edit_header,name='edit_header'),
    path('header_delete/<str:slug>',views.delete_header,name='delete_header'),


    path('add-cook', views.add_cook, name='add_cook'),
    path('<str:slug>/edit-cook',views.edit_cook,name='edit_cook'),
    path('cook_delete/<str:slug>',views.delete_cook,name='delete_cook'),
    
    # path('categories',views.all_categories,name='all_categories'),
    # path('categories/<int:id>',views.category_ads,name='category_ads'),
    # path('<int:id>/edit',views.post_edit,name='post_edit'),
    # path('delete/<int:id>/',views.delete_List, name='delete_list'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

def home(request):
    return redirect('kito:kito_list')

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls',namespace='accounts')),
    path('',  home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('kito.urls', namespace='kito')),
]
if settings.DEBUG:

    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kito/models.py
from django.db import models
from django.contrib.auth.models import User
from  django.utils import timezone
# Create your models here.

class Header(models.Model):
    
    userheader  = models.ForeignKey(User, related_name='userheader', on_delete=models.CASCADE,blank=True,null=True  )
    title       = models.CharField(max_length=100)
    content     = models.TextField(max_length=1000)
    image       = models.ImageField(upload_to='header/')
    created_at  = models.DateTimeField(auto_now=True) 
    update_at   = models.DateTimeField(auto_now_add=True)
    post_slug   = models.SlugField(blank=True, null=True)
     
    
    def save(self, *args, **kwargs):

        self.post_slug = self.title
        super(Header,self).save(*args, **kwargs)
        
    def __str__(self):

        return self.title

class Kito(models.Model):
    
    owner  = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE,blank=True,null=True  )
    title       = models.CharField(max_length=100)
    created_at  = models.DateTimeField(auto_now=True) 
    post_slug   = models.SlugField(blank=True, null=True)
    update_at   = models.DateTimeField(auto_now_add=True)
    img       = models.ImageField(upload_to='kito/')
    content     = models.TextField(max_length=1000)
    Kg          = models.IntegerField(default=1)
    day         = models.IntegerField(default=1)

 
    def save(self, *args, **kwargs):

        self.post_slug = self.title
        super(Kito,self).save(*args, **kwargs)
        
    def __str__(self):

        return self.title

class Comments(models.Model):
    user        = models.ForeignKey(User, related_name='userComment', on_delete=models.CASCADE,blank=True,null=True  )
    Kito       = models.ForeignKey('Kito', related_name='Comments_kito', on_delete=models.CASCADE  )
    comments    = models.TextField(blank=True, null=True)
    created_at  = models.DateTimeField(default=timezone.now)
    update_at   = models.DateTimeField(auto_now_add=True)




class SameEat(models.Model):
    
    user             = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE  )
    title            = models.CharField(max_length=100)
    created_at       = models.DateTimeField(auto_now=True) 
    post_slug        = models.SlugField(blank=True, null=True)
    update_at        = models.DateTimeField(auto_now_add=True)
    image            =  models.ImageField(upload_to='cook/')
    content          = models.TextField(max_length=1000)
    
   
    
    def save(self, *args, **kwargs):

        self.post_slug = self.title
        super(SameEat,self).save(*args, **kwargs)
        
    def __str__(self):

        return self.title

kito/forms.py
from django import forms
from .models import  Kito,SameEat,Header,Comments

class AddKitoDay(forms.ModelForm):
    class Meta:
        model= Kito
        fields = ['title','img','content','Kg','day']

class AddCook(forms.ModelForm):
    class Meta:
        model= SameEat
        fields = ['title','image','content']

class AddHeader(forms.ModelForm):
    class Meta:
        model= Header
        fields = ['title','image','content']
       


class CommentForm(forms.ModelForm):
	
	comments = forms.CharField(label='', widget = forms.Textarea(attrs={'class':'from-control','placeholder':'Text here ','rows':'3', 'cols':'50'}))
	class Meta:
		model= Comments
		fields = ['comments']

kito/views.py
from django.shortcuts import render,redirect,get_object_or_404,Http404
from  .models import Kito,SameEat,Header,Comments
from  .forms import AddKitoDay,AddCook,CommentForm,AddHeader
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
# Create your views here.
def kito_list(request):
    
    kito_post = Kito.objects.all()
    eat_cook = SameEat.objects.all()
    header = Header.objects.all()
   
    return render(request, 'kito_list.html',{'kito_post':kito_post,'eat_cook':eat_cook,'header':header})
def deleteList(request,slug):
    item = Kito.objects.get(post_slug=slug)

    if request.method == 'POST':
        item.delete()
        return redirect('/')
    context ={'item':item}
    return render(request,'delete_list.html',context)




@login_required
def add_daykito(request):
     
    if request.method == 'POST':
        form = AddKitoDay(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect('/')
    else:
        form =AddKitoDay()
    return render(request,'add-daykito.html',{'form':form })

@login_required
def add_haeder(request):
     
    if request.method == 'POST':
        form = AddHeader(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect('/')
    else:
        form =AddHeader()
    return render(request,'add-header.html',{'form':form})

@login_required
def edit_header(request, slug):
    
    edit_header = get_object_or_404(Header, post_slug=slug)
    if request.method == 'POST':
        form = AddHeader(request.POST, instance = edit_header)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.userheader = request.user
            new_form.save()
            return  redirect('/')
    else:
        form = AddHeader(instance = edit_header)
    context = {
        'form': form,
         
    }
    return render(request, 'edit_header.html', context)
@login_required
def delete_header(request,slug):
    item = Header.objects.get(post_slug=slug)

    if request.method == 'POST':
        item.delete()
        return redirect('/')
    context ={'item':item}
    return render(request,'delete_header.html',context)

@login_required
def edit(request, slug):
    
    edit_days = get_object_or_404(Kito, post_slug=slug)
    if request.method == 'POST':
        form = AddKitoDay(request.POST, instance = edit_days)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.owner = request.user
            new_form.save()
            return  redirect('/')
    else:
        form = AddKitoDay(instance = edit_days)
    context = {
        'form': form,
         
         
    }
    return render(request, 'create.html', context)


@login_required 
def add_cook(request):
     
    if request.method == 'POST':
        form = AddCook(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()
            return redirect('/')
    else:
        form =AddCook()
    return render(request,'add-cook.html',{'form':form})

@login_required
def edit_cook(request, slug):
     
    edit_cook = get_object_or_404(SameEat, post_slug=slug)
    if request.method == 'POST':
        form = AddCook(request.POST, instance = edit_cook)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return  redirect('/')
    else:
        form = AddCook(instance = edit_cook)
    context = {
        'form': form,
         
    }
    return render(request, 'edit_cook.html', context)

@login_required
def delete_cook(request,slug):
    item = Header.objects.get(post_slug=slug)

    if request.method == 'POST':
        item.delete()
        return redirect('/')
    context ={'item':item}
    return render(request,'delete_cook.html',context)

kito/templates/add-cook.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Add Cook Kito </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/add-daykito.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Add Kito Day</h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/add-header.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Add New Header </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Add</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/comments.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <!-- ***** Preloader Start ***** -->
   {% include 'navbar.html' %}
<div class="container">
        
        <div class="row">
            <div class="col-md-12 mb-5">
                <div class="section-heading text-center">
                    <h2><strong>Comments</strong></h2>
                </div>
            </div>
            <div class="col-md-6 mb-5 mb-md-0">

                <form action="." method="POST" class="comment-form" enctype="multipart/form-data">
                    {% csrf_token %}
                  
                    <h2><strong>Comments</strong></h2>
                 
                    {% bootstrap_form form %}
                         
                    <input type="hidden" name="comment_id" value="{{comment.id}}" >
                    <input type="submit" class="btn btn-dark  px-4 py-3" value="Submit">
                </form>
            </div>


        </div>
                </div>
                


{% endblock %}
        

kito/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Edit Kito Days </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Save Edit</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/delete_cook.html
 


{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <p>Are you sure you want to delete "{{item}}"</p>
             
             
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
               <button type="submit" id="form-submit" name="Comfirm" class="filled-button">Comfirm</button>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/delete_header.html
 


{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <p>Are you sure you want to delete "{{item}}"</p>
             
             
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
               <button type="submit" id="form-submit" name="Comfirm" class="filled-button">Comfirm</button>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/delete_list.html
 


{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <p>Are you sure you want to delete "{{item}}"</p>
             
             
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
               <button type="submit" id="form-submit" name="Comfirm" class="filled-button">Comfirm</button>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/edit_cook.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Edit Cook Kito </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Save Edit</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/edit_header.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
    <div class="send-messageo">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mt-5">
            <div class="section-heading" style="margin-top: 70px;">
              <h2>Edit Header Kito </h2>
            </div>
          </div>

          <div class="col-md-8 m-auto">
            <div class="contact-form">
              <form id="contact" action="" method="post" action="" enctype="multipart/form-data">
              	{% csrf_token %}
              	{% bootstrap_form form %}
                <div class="row">

                  <div class="col-lg-12">
                    <fieldset>
{% buttons %}
                      <button type="submit" id="form-submit" class="filled-button">Save Edit</button>
{% endbuttons %}
                    </fieldset>
                  </div>

                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>

   


{% endblock %}

kito/templates/kito_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <!-- ***** Preloader Start ***** -->
   {% include 'navbar.html' %}
   {% include  'header.html' %}
    <!-- Banner Ends Here -->
<div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Latest Products</h2>
              <a href="products.html">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
          {% for post in kito_post %}
          <div class="col-md-4">
            <div class="product-item">
              
              <a href="#"><img src="{{ post.img.url }}" alt=""></a>

              <div class="down-content">
                <a href="{% url 'kito:add_daykito' %}"><h4>{{post.title}}</h4></a>
                <h6>Kg{{post.Kg}}</h6>
                <p>{{post.content}}.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                {% if request.user.is_authenticated %}
               
                  <span><a href="{% url 'kito:comments' post.id %">ملاحظات  </a></span>
        <ul class="stars">
                  <li><a href="{% url 'kito:edit' post.post_slug %}"><i class="">تعديل   </i> </li>

                     

                  <li><a href="{% url 'kito:list_delete' post.post_slug  %}" id="delete"><i class="">حذف   </i></a> </li>

                 
                </ul> 
                {% endif %}
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    
 


    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading text-center" >
              <h2 style="font-size:60px;">وصفات كيتو</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

        <div class="banner header-text">
      <div class="owl-banner owl-carousel">

         {% for eat in eat_cook %}
        <div class="banner-item-01">
          <div class="text-content">
            <h4>{{eat.title}}</h4>
            <h2>{{eat.content}}</h2>
             <button><small> <a href="{% url 'kito:edit_cook' eat.post_slug %}">Edit Cook</a></small></button>
             <button><small> <a href="{% url 'kito:delete_cook' eat.post_slug %}">Delete Cook</a></small></button>
          </div>
        </div>
         {% endfor %}
      </div>
    </div>

{% endblock %}

kito/templates/same_eat.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 
    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>About Sixteen Clothing</h2>
            </div>
          </div>
          <div class="col-md-6">
              {% for cook in Eat_cook %}
            <div class="left-content">
              <h4>Looking for the best products?</h4>
              <p><a rel="nofollow" href="https://templatemo.com/tm-546-sixteen-clothing" target="_parent">This template</a> is free to use for your business websites. However, you have no permission to redistribute the downloadable ZIP file on any template collection website. <a rel="nofollow" href="https://templatemo.com/contact">Contact us</a> for more info.</p>
              <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul>
              <a href="about.html" class="filled-button">Read More</a>
            </div>
            {% endfor %}
          </div>

          <div class="col-md-6">
            <div class="right-image">
              <img src="assets/images/feature-image.jpg" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <h4>Creative &amp; Unique <em>Sixteen</em> Products</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corporis amet elite author nulla.</p>
                </div>
                <div class="col-md-4">
                  <a href="#" class="filled-button">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}